[package]
name = "rust_parallel"
version = "0.1.0"
edition = "2021"  # ※2024って書いてたけどRustの正式サポートはまだ2021やから一旦これにしとこ！

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18.3", features = ["extension-module"] }
rayon = "1.6"
